---
- name: Deploy application to EC2
  hosts: web
  become: false

  tasks:

    - name: Change to project directory and pull latest Docker images
      shell: |
        cd /home/ubuntu/ci-cd-proyect
        docker compose pull

    - name: Restart the application
      shell: |
        cd /home/ubuntu/ci-cd-proyect
        docker compose up -d

    - name: Verify running containers
      shell: |
        docker ps
      register: docker_ps

    - name: Display running containers
      debug:
        var: docker_ps.stdout_lines